# $schema = "node_modules/wrangler/config-schema.json"
name = "tutor-project"
compatibility_date = "2025-09-02"
compatibility_flags = ["nodejs_compat"]
main = "src/server.ts"

[[durable_objects.bindings]]
name = "TutorAgent"
class_name = "TutorAgent"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TutorAgent"]

[[d1_databases]]
binding = "DB"
database_name = "tutor-db"
database_id = "fee051e5-6124-44f2-8fa1-aef1db0aba96"
migrations_dir = "drizzle"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
