/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AgentsSplatRouteImport } from './routes/agents/$'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedNotebookIDSidebarRouteImport } from './routes/_authenticated/$notebookID/_sidebar'
import { Route as AuthenticatedNotebookIDSidebarPanelRouteImport } from './routes/_authenticated/$notebookID/_sidebar/_panel'
import { Route as AuthenticatedNotebookIDSidebarPanelIndexRouteImport } from './routes/_authenticated/$notebookID/_sidebar/_panel.index'
import { Route as AuthenticatedNotebookIDSidebarPanelChatIDRouteImport } from './routes/_authenticated/$notebookID/_sidebar/_panel.$chatID'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AgentsSplatRoute = AgentsSplatRouteImport.update({
  id: '/agents/$',
  path: '/agents/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotebookIDSidebarRoute =
  AuthenticatedNotebookIDSidebarRouteImport.update({
    id: '/$notebookID/_sidebar',
    path: '/$notebookID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotebookIDSidebarPanelRoute =
  AuthenticatedNotebookIDSidebarPanelRouteImport.update({
    id: '/_panel',
    getParentRoute: () => AuthenticatedNotebookIDSidebarRoute,
  } as any)
const AuthenticatedNotebookIDSidebarPanelIndexRoute =
  AuthenticatedNotebookIDSidebarPanelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNotebookIDSidebarPanelRoute,
  } as any)
const AuthenticatedNotebookIDSidebarPanelChatIDRoute =
  AuthenticatedNotebookIDSidebarPanelChatIDRouteImport.update({
    id: '/$chatID',
    path: '/$chatID',
    getParentRoute: () => AuthenticatedNotebookIDSidebarPanelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/agents/$': typeof AgentsSplatRoute
  '/$notebookID': typeof AuthenticatedNotebookIDSidebarPanelRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$notebookID/$chatID': typeof AuthenticatedNotebookIDSidebarPanelChatIDRoute
  '/$notebookID/': typeof AuthenticatedNotebookIDSidebarPanelIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/agents/$': typeof AgentsSplatRoute
  '/': typeof AuthenticatedIndexRoute
  '/$notebookID': typeof AuthenticatedNotebookIDSidebarPanelIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$notebookID/$chatID': typeof AuthenticatedNotebookIDSidebarPanelChatIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/agents/$': typeof AgentsSplatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$notebookID/_sidebar': typeof AuthenticatedNotebookIDSidebarRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/$notebookID/_sidebar/_panel': typeof AuthenticatedNotebookIDSidebarPanelRouteWithChildren
  '/_authenticated/$notebookID/_sidebar/_panel/$chatID': typeof AuthenticatedNotebookIDSidebarPanelChatIDRoute
  '/_authenticated/$notebookID/_sidebar/_panel/': typeof AuthenticatedNotebookIDSidebarPanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/agents/$'
    | '/$notebookID'
    | '/api/auth/$'
    | '/$notebookID/$chatID'
    | '/$notebookID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/agents/$'
    | '/'
    | '/$notebookID'
    | '/api/auth/$'
    | '/$notebookID/$chatID'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/settings'
    | '/agents/$'
    | '/_authenticated/'
    | '/_authenticated/$notebookID/_sidebar'
    | '/api/auth/$'
    | '/_authenticated/$notebookID/_sidebar/_panel'
    | '/_authenticated/$notebookID/_sidebar/_panel/$chatID'
    | '/_authenticated/$notebookID/_sidebar/_panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AgentsSplatRoute: typeof AgentsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/agents/$': {
      id: '/agents/$'
      path: '/agents/$'
      fullPath: '/agents/$'
      preLoaderRoute: typeof AgentsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$notebookID/_sidebar': {
      id: '/_authenticated/$notebookID/_sidebar'
      path: '/$notebookID'
      fullPath: '/$notebookID'
      preLoaderRoute: typeof AuthenticatedNotebookIDSidebarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$notebookID/_sidebar/_panel': {
      id: '/_authenticated/$notebookID/_sidebar/_panel'
      path: ''
      fullPath: '/$notebookID'
      preLoaderRoute: typeof AuthenticatedNotebookIDSidebarPanelRouteImport
      parentRoute: typeof AuthenticatedNotebookIDSidebarRoute
    }
    '/_authenticated/$notebookID/_sidebar/_panel/': {
      id: '/_authenticated/$notebookID/_sidebar/_panel/'
      path: '/'
      fullPath: '/$notebookID/'
      preLoaderRoute: typeof AuthenticatedNotebookIDSidebarPanelIndexRouteImport
      parentRoute: typeof AuthenticatedNotebookIDSidebarPanelRoute
    }
    '/_authenticated/$notebookID/_sidebar/_panel/$chatID': {
      id: '/_authenticated/$notebookID/_sidebar/_panel/$chatID'
      path: '/$chatID'
      fullPath: '/$notebookID/$chatID'
      preLoaderRoute: typeof AuthenticatedNotebookIDSidebarPanelChatIDRouteImport
      parentRoute: typeof AuthenticatedNotebookIDSidebarPanelRoute
    }
  }
}

interface AuthenticatedNotebookIDSidebarPanelRouteChildren {
  AuthenticatedNotebookIDSidebarPanelChatIDRoute: typeof AuthenticatedNotebookIDSidebarPanelChatIDRoute
  AuthenticatedNotebookIDSidebarPanelIndexRoute: typeof AuthenticatedNotebookIDSidebarPanelIndexRoute
}

const AuthenticatedNotebookIDSidebarPanelRouteChildren: AuthenticatedNotebookIDSidebarPanelRouteChildren =
  {
    AuthenticatedNotebookIDSidebarPanelChatIDRoute:
      AuthenticatedNotebookIDSidebarPanelChatIDRoute,
    AuthenticatedNotebookIDSidebarPanelIndexRoute:
      AuthenticatedNotebookIDSidebarPanelIndexRoute,
  }

const AuthenticatedNotebookIDSidebarPanelRouteWithChildren =
  AuthenticatedNotebookIDSidebarPanelRoute._addFileChildren(
    AuthenticatedNotebookIDSidebarPanelRouteChildren,
  )

interface AuthenticatedNotebookIDSidebarRouteChildren {
  AuthenticatedNotebookIDSidebarPanelRoute: typeof AuthenticatedNotebookIDSidebarPanelRouteWithChildren
}

const AuthenticatedNotebookIDSidebarRouteChildren: AuthenticatedNotebookIDSidebarRouteChildren =
  {
    AuthenticatedNotebookIDSidebarPanelRoute:
      AuthenticatedNotebookIDSidebarPanelRouteWithChildren,
  }

const AuthenticatedNotebookIDSidebarRouteWithChildren =
  AuthenticatedNotebookIDSidebarRoute._addFileChildren(
    AuthenticatedNotebookIDSidebarRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedNotebookIDSidebarRoute: typeof AuthenticatedNotebookIDSidebarRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedNotebookIDSidebarRoute:
    AuthenticatedNotebookIDSidebarRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AgentsSplatRoute: AgentsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
